import { COLOR, FONT, BORDER } from './global';

export const FIELD = {
  SIZE: {
    MD: '28rem',
  },
  TEXT_COLOR: COLOR.STANDARD,
  ICON_COLOR: COLOR.BG[500],
  PLACE_HOLDER_COLOR: COLOR.PLACE_HOLDER,
  BG_COLOR: COLOR.BG[100],
  BG_COLOR_FOCUS: COLOR.BG[200],
  BORDER_RADIUS: BORDER.RADIUS,
  FONT_SIZE: FONT.SIZE.SM,
  FONT: FONT.FAMILY.BODY,
  TRANSITION: '0.2s all',
};
